name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' # optional
      - name: Build with Maven
        working-directory: .
        run: mvn -B package
      #- run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      #- run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          ls target
          pwd
          java -jar target/Hello-2025-1.0-SNAPSHOT.jar
      - name: Dockerization
        working-directory: .
        run: |
          docker build -t seminar-2025 --file ./src/main/docker/Dockerfile .
          docker image ls
          docker run seminar-2025
      - run: echo "🍏 This job's status is ${{ job.status }}."
